// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventMessageTopic int32

const (
	EventMessageTopic_EventMessage EventMessageTopic = 0
)

var EventMessageTopic_name = map[int32]string{
	0: "EventMessage",
}

var EventMessageTopic_value = map[string]int32{
	"EventMessage": 0,
}

func (x EventMessageTopic) String() string {
	return proto.EnumName(EventMessageTopic_name, int32(x))
}

func (EventMessageTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type MessageEntity struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Users                []string `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageEntity) Reset()         { *m = MessageEntity{} }
func (m *MessageEntity) String() string { return proto.CompactTextString(m) }
func (*MessageEntity) ProtoMessage()    {}
func (*MessageEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MessageEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageEntity.Unmarshal(m, b)
}
func (m *MessageEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageEntity.Marshal(b, m, deterministic)
}
func (m *MessageEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageEntity.Merge(m, src)
}
func (m *MessageEntity) XXX_Size() int {
	return xxx_messageInfo_MessageEntity.Size(m)
}
func (m *MessageEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageEntity.DiscardUnknown(m)
}

var xxx_messageInfo_MessageEntity proto.InternalMessageInfo

func (m *MessageEntity) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *MessageEntity) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *MessageEntity) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterEnum("message.EventMessageTopic", EventMessageTopic_name, EventMessageTopic_value)
	proto.RegisterType((*MessageEntity)(nil), "message.MessageEntity")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xfc, 0xb9,
	0x78, 0x7d, 0x21, 0x4c, 0xd7, 0xbc, 0x92, 0xcc, 0x92, 0x4a, 0x21, 0x11, 0x2e, 0xd6, 0x92, 0xfc,
	0x82, 0xcc, 0x64, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x07, 0x24, 0x5a, 0x5a, 0x9c,
	0x5a, 0x54, 0x2c, 0xc1, 0xa4, 0xc0, 0x0c, 0x12, 0x05, 0x73, 0x84, 0x84, 0xb8, 0x58, 0x92, 0xf2,
	0x53, 0x2a, 0x25, 0x98, 0xc1, 0x4a, 0xc1, 0x6c, 0x2d, 0x55, 0x2e, 0x41, 0xd7, 0xb2, 0xd4, 0xbc,
	0x12, 0xa8, 0xa9, 0x21, 0x60, 0xed, 0x02, 0x5c, 0x3c, 0xc8, 0x82, 0x02, 0x0c, 0x49, 0x6c, 0x60,
	0x77, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x3f, 0x6c, 0x9a, 0x98, 0x00, 0x00, 0x00,
}
